### PR TITLE
fix: avoid unstable duration_constructors so torchft builds on Rust < 1.91

### LINKED ISSUE #330: Need to specify minimal rust version to build
- Building rust v. 1.88 gives the error below. Relevant code is under [src/net.rs](https://github.com/meta-pytorch/torchft/blame/4157be16e7ab2b9e2471e48355eb7d87a6c0fd07/src/net.rs#L20). PR is #297, which cites rust 1.91 introducing `Duration::from_mins`
- Perhaps the README.md could be updated to explicitly state Rust 1.91 as the minimal version needed.

```
Building wheels for collected packages: torchft
  Building editable for torchft (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building editable for torchft (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Running `maturin pep517 build-wheel -i /nfs/jinsun/venv/rfsdp/bin/python3 --compatibility off --editable`
      📦 Including license file `LICENSE`
      🍹 Building a mixed python/rust project
      🐍 Found CPython 3.13 at /nfs/jinsun/venv/rfsdp/bin/python3
      🔗 Found pyo3 bindings
      📡 Using build options features from pyproject.toml
         Compiling torchft v0.1.1 (/nfs/jinsun/torchft)
      error[E0658]: use of unstable library feature `duration_constructors`
        --> src/net.rs:20:36
         |
      20 |         .http2_keep_alive_interval(Duration::from_mins(1))
         |                                    ^^^^^^^^^^^^^^^^^^^
         |
         = note: see issue #120301 <https://github.com/rust-lang/rust/issues/120301> for more information
      
      For more information about this error, try `rustc --explain E0658`.
      error: could not compile `torchft` (lib) due to 1 previous error
      💥 maturin failed
        Caused by: Failed to build a native library through cargo
        Caused by: Cargo build finished with "exit status: 101": `env -u CARGO PYO3_BUILD_EXTENSION_MODULE="1" PYO3_ENVIRONMENT_SIGNATURE="cpython-3.13-64bit" PYO3_PYTHON="/nfs/jinsun/venv/rfsdp/bin/python3" PYTHON_SYS_EXECUTABLE="/nfs/jinsun/venv/rfsdp/bin/python3" "cargo" "rustc" "--profile" "release" "--features" "pyo3/extension-module" "--message-format" "json-render-diagnostics" "--manifest-path" "/nfs/jinsun/torchft/Cargo.toml" "--lib" "--crate-type" "cdylib"`
      Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/nfs/jinsun/venv/rfsdp/bin/python3', '--compatibility', 'off', '--editable'] returned non-zero exit status 1
      [end of output]
```

### PR DESCRIPTION
**Pull request by ajinkyajawale14499**
## Summary

`src/net.rs` calls `Duration::from_mins(1)`. `Duration::from_mins`/`from_hours` (the
`duration_constructors` feature, rust-lang/rust#120301) were unstable until Rust 1.91, so building
torchft on older stable Rust fails with:

```
error[E0658]: use of unstable library feature `duration_constructors`
  --> src/net.rs:20:36
```

This was reported on Rust 1.88 (#330). CI did not catch it because every workflow installs
`--default-toolchain=stable`, which is now >= 1.91.

The issue suggests documenting Rust 1.91 as the minimum. This PR instead removes the need for it:
`from_mins(1)` is exactly `from_secs(60)`, so switching to the stable constructor lets torchft build
on the older stable Rust the reporter (and many distro/conda/CI environments) actually have, rather
than forcing everyone onto a bleeding-edge toolchain for a trivial constant.

## Changes

The API was used at four sites (one in production, three in tests), all converted to the identical
`from_secs(...)` value:

- `src/net.rs` — `from_mins(1)` -> `from_secs(60)` (HTTP/2 keep-alive interval)
- `src/timeout.rs` (tests) — `from_hours(3)`/`from_mins(3)` -> `from_secs(3 * SECONDS_IN_HOUR)` /
  `from_secs(3 * SECONDS_IN_MINUTE)`, reusing the module's existing constants so the test mirrors the
  parser it covers
- `src/lighthouse.rs` (test) — `from_hours(10)` -> `from_secs(10 * 60 * 60)`

No behaviour change: each replacement is the same `Duration`.

## Verification

- `rustup toolchain install 1.88.0`
- On `main`: `cargo +1.88.0 check --tests` reproduces `E0658` at all four sites.
- With this change: `cargo +1.88.0 check --tests` compiles clean (build floor dropped to <= 1.88).
- `cargo +nightly fmt --check` clean; `cargo +stable check --tests` green.
- `grep -rn "from_mins\|from_hours\|from_days" --include='*.rs'` returns nothing.

## Follow-up

If you would still like the minimum Rust version documented explicitly, I am happy to add a
`rust-version` field to `Cargo.toml` plus a README note in a follow-up. Removing the unstable API
first means that floor can stay conservative instead of being pinned to 1.91.

Closes #330

### CODE REVIEW

**Review by d4l3k — APPROVED** [review]
LGTM
